services: 
  orders_api_db: 
    image: mysql:latest
    container_name: orders_api_db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_api
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306

