services: 
  orders_api_db: 
    image: mysql:latest
    container_name: orders_api_db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_api
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
